### ISSUE TITLE
Git Merge Conflict

### ISSUE THREAD

**Issue by tahoward** [hexparrot/mineos-docker#10]
Image: hexparrot/mineos:node-crux

On start-up a git merge conflict occurs attempting to merge `https://github.com/hexparrot/mineos-node`:
```
Created user: admin
Generating Self-Signed SSL...
Generating a 1024 bit RSA private key
..++++++
..++++++
writing new private key to '.tmpkey.pem'
-----
writing RSA key
remote: Counting objects: 5184, done.
remote: Compressing objects: 100% (1976/1976), done.
remote: Total 5184 (delta 3194), reused 5102 (delta 3121), pack-reused 0
Receiving objects: 100% (5184/5184), 2.47 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3194/3194), completed with 43 local objects.
From https://github.com/hexparrot/mineos-node
   bea277f..f6bc23f  master     -> origin/master
 * [new tag]         v1.0       -> v1.0
 * [new tag]         v1.0.1     -> v1.0.1
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.2     -> v1.1.2
 * [new tag]         v1.1.3     -> v1.1.3
 * [new tag]         v1.1.4     -> v1.1.4
 * [new tag]         v1.1.7     -> v1.1.7
 * [new tag]         v1.1.8     -> v1.1.8
 * [new tag]         v1.2.0     -> v1.2.0
Updating bea277f..f6bc23f
error: Your local changes to the following files would be overwritten by merge:
        webui.js
Please, commit your changes or stash them before you can merge.
Aborting
```

**Comment by hexparrot** [comment]
I'm not ... _too_ familiar with docker, enough to know why this error would come up.  The error suggests that the local copy has been changed (and thus it's somehow modified from any version that exists in the official repo). 

webui.js isn't something that has been touched in ages, and the commit you're coming from is pretty old: Sep 7, 2016.  That said, I think that this is probably a one-time occurrence and can be solved relatively easily.

I'd recommend you attach to your MineOS container and run the normal reset mechanism:

1) cd /usr/games/minecraft && bash reset_webui.sh

or

2) cd /usr/games/minecraft && git fetch && git reset --hard origin/master

**Comment by tahoward** [comment]
My best guess is the combination of these two lines are causing the issue. Not exactly sure why a git fetch is being performed right after the initial clone...

https://github.com/hexparrot/mineos-docker/blob/master/crux/Dockerfile#L47
https://github.com/hexparrot/mineos-docker/blob/master/crux/entrypoint.sh#L45

**Comment by tahoward** [comment]
The docker hub builds from this repository appear deprecated after checking the mineos-node commit hashes; which are about a year behind mineos-node master.
