### ISSUE TITLE
for updating the UI in docker

### ISSUE THREAD

**Issue by changemenemo** [hexparrot/mineos-docker#3]
Hi, 
So as you asked me to do I've open an issue for the update of the UI since you didn't put anything as automatic job for updating the commit of the webui. 

First maybe at the end of your dockerfile:
do a chmod +x to reset_webui.sh and update.webui.sh (not sur of the name anymore) because they are actually not executables.

make a shell script :
`#!/bin/bash

supervisorctl stop mineos
reset_webui.sh
update_webui.sh
supervisorctl start mineos`

then also create a cronjob in /etc/daily: 
with something like 1 \* \* \* \* shellscript

but of course I don't what you put exactly in those script since I'm not an expert in shellscripting.
What do you think?

**Comment by hexparrot** [comment]
`chmod +x` has a limited use because for the most part, the shell scripts can be executed by being prefixed with `/bin/bash reset_webui.sh`.  It's a convenience, but not a big deal, or at least, probably not one enough to warrant re-creating the docker image.

Also, You don't need to reset _and_ update.  One or the other is fine;  considering that a docker instance will greatly determanual edits to the source code in general, updating the webui should be more than sufficient and resetting is overkill.

**Comment by changemenemo** [comment]
Mmmmh okey maybe yes but I can assure you at least that update script doesn’t work because it has asked me to reset the webui each time I tried…. So you should maybe investigate this thing. 
I don’t know either why when I try to recreate the docker it didn’t download the last commit.

Would you like that we do some test ?
Anyway i've stop - rm the container and restart it and again I've been with commit 9bc5b3f and your actual commit is :  8dc5529  
Since your interface is not installed on the volume where the configuration for the servers is : so the problem is in your dockerfile

**Comment by hexparrot** [comment]
Can you provide any more detail about the steps you're taking and the results you're getting (vs. what you expect)?

I just built node-jessie from the Dockerfile and not only does it download exactly the latest commit, I'm also able to use `update_webui.sh`, which I can verify updates _without_ resetting.

```
root@willonubuntu:/usr/games# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                                               NAMES
9b60ffc378a1        mineos:latest       "/entrypoint.sh /usr/"   About a minute ago   Up About a minute   0.0.0.0:8443->8443/tcp, 0.0.0.0:25565->25565/tcp, 25566-25570/tcp   determined_kowalevski
root@willonubuntu:/usr/games# docker exec -it 9b60ffc378a1 /bin/bash
root@9b60ffc378a1:/# cd /usr/games/minecraft/
root@9b60ffc378a1:/usr/games/minecraft# ls
LICENSE.md  generate-sslcert.sh  mineos.conf        node_modules    server.js   update_webui.sh
README.md   html                 mineos.js          package.json    service.js  webui.js
auth.js     init                 mineos_console.js  reset_webui.sh  test
root@9b60ffc378a1:/usr/games/minecraft# /bin/bash update_webui.sh
Script execution started on: Fri Sep  2 18:03:50 UTC 2016
Updating mineos-node repository...OK
Pulling master branch...From https://github.com/hexparrot/mineos-node
 * branch            master     -> FETCH_HEAD
OK
Updating npm dependencies...OK
Setting node javascript files to executable...OK
Script execution ended on: Fri Sep  2 18:03:53 UTC 2016
root@9b60ffc378a1:/usr/games/minecraft#

```

**Comment by changemenemo** [comment]
Okey.  But I would really like to understand why you build from the source in place of first doing a pull from the hub like we are all supposed to do? So sorry but I expect to work with the tools that I have from docker and not doing a git clone and all this crap... So if you don't mind can you just do a docker pull hexparrot/mineos:node-Jessie?
Thanks in advance

Télécharger Outlook pour Androidhttps://aka.ms/ghei36

On Fri, Sep 2, 2016 at 8:06 PM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you provide any more detail about the steps you're taking and the results you're getting (vs. what you expect)?

I just built node-jessie from the Dockerfile and not only does it download exactly the latest commit, I'm also able to use update_webui.sh, which I can verify updates without resetting.

root@willonubuntu:/usr/games# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                                               NAMES
9b60ffc378a1        mineos:latest       "/entrypoint.sh /usr/"   About a minute ago   Up About a minute   0.0.0.0:8443->8443/tcp, 0.0.0.0:25565->25565/tcp, 25566-25570/tcp   determined_kowalevski
root@willonubuntu:/usr/games# docker exec -it 9b60ffc378a1 /bin/bash
root@9b60ffc378a1:/# cd /usr/games/minecraft/
root@9b60ffc378a1:/usr/games/minecraft# ls
LICENSE.md  generate-sslcert.sh  mineos.conf        node_modules    server.js   update_webui.sh
README.md   html                 mineos.js          package.json    service.js  webui.js
auth.js     init                 mineos_console.js  reset_webui.sh  test
root@9b60ffc378a1:/usr/games/minecraft# /bin/bash update_webui.sh
Script execution started on: Fri Sep  2 18:03:50 UTC 2016
Updating mineos-node repository...OK
Pulling master branch...From https://github.com/hexparrot/mineos-node
- branch            master     -> FETCH_HEAD
  OK
  Updating npm dependencies...OK
  Setting node javascript files to executable...OK
  Script execution ended on: Fri Sep  2 18:03:53 UTC 2016
  root@9b60ffc378a1:/usr/games/minecraft#

##

**Comment by hexparrot** [comment]
Really, whichever image is used is irrelevant.  I happened to use one I built from the dockerfile but you would get exactly the same results using the one pulled from the hub:

```
root@willonubuntu:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mineos              latest              59e51ec3503a        2 hours ago         545.5 MB
debian              jessie              031143c1c662        2 days ago          125.1 MB
hexparrot/mineos    node-jessie         ca1ad8060be2        10 weeks ago        519.9 MB
root@willonubuntu:~# docker run -itd -p 8443:8443 -p 25565:25565 -e USER_PASSWORD=mypass -v /var/games/minecraft:/var/games/minecraft hexparrot/mineos:node-jessie
3f30539bc74eb86b02471be42d2973234297fac99c19c457381c9d237e901d53
root@willonubuntu:~# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                               NAMES
3f30539bc74e        hexparrot/mineos:node-jessie   "/entrypoint.sh /usr/"   2 seconds ago       Up 2 seconds        0.0.0.0:8443->8443/tcp, 0.0.0.0:25565->25565/tcp, 25566-25570/tcp   cocky_babbage
root@willonubuntu:~# docker exec -it 3f30539bc74e /bin/bash
root@3f30539bc74e:/# cd /usr/games/minecraft/
root@3f30539bc74e:/usr/games/minecraft# ls
LICENSE.md  generate-sslcert.sh  mineos.conf        node_modules    server.js   update_webui.sh
README.md   html                 mineos.js          package.json    service.js  webui.js
auth.js     init                 mineos_console.js  reset_webui.sh  test
root@3f30539bc74e:/usr/games/minecraft# git log -n 1 | grep commit
commit 9bc5b3f30010465b2307b5625cfdd82c818d19c3
root@3f30539bc74e:/usr/games/minecraft# git fetch
remote: Counting objects: 5066, done.
remote: Compressing objects: 100% (1934/1934), done.
remote: Total 5066 (delta 3110), reused 5001 (delta 3045), pack-reused 0
Receiving objects: 100% (5066/5066), 2.36 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3110/3110), completed with 43 local objects.
From https://github.com/hexparrot/mineos-node
   9bc5b3f..8dc5529  master     -> origin/master
 * [new tag]         v1.0       -> v1.0
 * [new tag]         v1.0.1     -> v1.0.1
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.2     -> v1.1.2
 * [new tag]         v1.1.3     -> v1.1.3
 * [new tag]         v1.1.4     -> v1.1.4
 * [new tag]         v1.1.5     -> v1.1.5
 * [new tag]         v1.1.6     -> v1.1.6
root@3f30539bc74e:/usr/games/minecraft# git reset --hard origin/master
HEAD is now at 8dc5529 monospaced and nocaps for logfile headers
root@3f30539bc74e:/usr/games/minecraft# npm install
root@3f30539bc74e:/usr/games/minecraft# supervisorctl restart mineos
mineos: stopped
mineos: started
root@3f30539bc74e:/usr/games/minecraft# git log -n 1 | grep commit
commit 8dc5529d095d7b074f956eac6deb7f0eac729773
root@3f30539bc74e:/usr/games/minecraft#

```

Realistically, though, users should probably never have to do this; they would just pull from the hub.  However, seeing as how mineos-docker has accrued so little actual interest, that explains the little amount of attention spent making sure each new commit has a new, updated docker image on the hub.

The associated costs with keeping each hub image up to date isn't all that great, but it seems to be pretty great compared to the amount of value it seemingly offers users (on the whole). Arguably, I don't need so many different docker images at all--perhaps I could reduce it to just one...but at some point, either I'll have to commit fully to docker being a primary deployment method, or I'll just anticipate anybody using it will be able to navigate their way around docker and update as shown above.

**Comment by changemenemo** [comment]
I understand you very well but could you at least accept that maybe something is not happening correctly here?
As a user we don't control anything and don't have any grip on how the image or things like that are processed since we just do docker pull etc...  So can you accept that?
So how do we debug this situation?  Do you really want that I prove you the problem by putting out the commit?  I already did by putting you the commit I had earlier on the webui by rerun a new container...
So what do you want proof of what version is download like you did?
Is that the command line to do for that? git log -n 1 | grep commit

T?l?charger Outlook pour https://aka.ms/ghei36 Android

De : William Dizon
Envoy? : vendredi 2 septembre 22:52
Objet : Re: [hexparrot/mineos-docker] for updating the UI in docker (#3)
? : hexparrot/mineos-docker
Cc : boistordu, Author

Really, whichever image is used is irrelevant. I happened to use one I built from the dockerfile but you would get exactly the same results using the one pulled from the hub:

root@willonubuntu:~# docker images REPOSITORY TAG IMAGE ID CREATED SIZE mineos latest 59e51ec3503a 2 hours ago 545.5 MB debian jessie 031143c1c662 2 days ago 125.1 MB hexparrot/mineos node-jessie ca1ad8060be2 10 weeks ago 519.9 MB root@willonubuntu:~# docker run -itd -p 8443:8443 -p 25565:25565 -e USER_PASSWORD=mypass -v /var/games/minecraft:/var/games/minecraft hexparrot/mineos:node-jessie 3f30539bc74eb86b02471be42d2973234297fac99c19c457381c9d237e901d53 root@willonubuntu:~# docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 3f30539bc74e hexparrot/mineos:node-jessie "/entrypoint.sh /usr/" 2 seconds ago Up 2 seconds 0.0.0.0:8443->8443/tcp, 0.0.0.0:25565->25565/tcp, 25566-25570/tcp cocky_babbage root@willonubuntu:~# docker exec -it 3f30539bc74e /bin/bash root@3f30539bc74e:/# cd /usr/games/minecraft/ root@3f30539bc74e:/usr/games/minecraft# ls LICENSE.md generate-sslcert.sh mineos.conf node_modules server.js update_webui.sh README.md html mineos.js package.json service.js webui.js auth.js init mineos_console.js reset_webui.sh test root@3f30539bc74e:/usr/games/minecraft# git log -n 1 | grep commit commit 9bc5b3f30010465b2307b5625cfdd82c818d19c3 root@3f30539bc74e:/usr/games/minecraft# git fetch remote: Counting objects: 5066, done. remote: Compressing objects: 100% (1934/1934), done. remote: Total 5066 (delta 3110), reused 5001 (delta 3045), pack-reused 0 Receiving objects: 100% (5066/5066), 2.36 MiB | 0 bytes/s, done. Resolving deltas: 100% (3110/3110), completed with 43 local objects. From https://github.com/hexparrot/mineos-node 9bc5b3f..8dc5529 master -> origin/master \* [new tag] v1.0 -> v1.0 \* [new tag] v1.0.1 -> v1.0.1 \* [new tag] v1.1.0 -> v1.1.0 \* [new tag] v1.1.1 -> v1.1.1 \* [new tag] v1.1.2 -> v1.1.2 \* [new tag] v1.1.3 -> v1.1.3 \* [new tag] v1.1.4 -> v1.1.4 \* [new tag] v1.1.5 -> v1.1.5 \* [new tag] v1.1.6 -> v1.1.6 root@3f30539bc74e:/usr/games/minecraft# git reset --hard origin/master HEAD is now at 8dc5529 monospaced and nocaps for logfile headers root@3f30539bc74e:/usr/games/minecraft# npm install root@3f30539bc74e:/usr/games/minecraft# supervisorctl restart mineos mineos: stopped mineos: started root@3f30539bc74e:/usr/games/minecraft# git log -n 1 | grep commit commit 8dc5529d095d7b074f956eac6deb7f0eac729773 root@3f30539bc74e:/usr/games/minecraft#

##

**Comment by hexparrot** [comment]
> As a user we don't control anything and don't have any grip on how the image or things like that are processed since we just do docker pull etc...  So can you accept that?

What exactly are you asking of me?  In the first example, I demonstrated that a `docker build .` approach created a new, modern image with the most recent webui.  You dismissed this because you know that using the hub is a far more convenient means than building it manually.

I followed that up by demonstrating a hexparrot/mineos:node-jessie image--the one on the hub--could be downloaded, started, and then shown to be updated to a more modern webui commit.  The docker hub version started as 9bc5b3f30010465b2307b5625cfdd82c818d19c3 and then was updated and successfully started as commit 8dc5529d095d7b074f956eac6deb7f0eac729773.

So my question is: **what is the problem you are having?**

Is your concern that the docker hub image isn't _already_ 8dc5529d095d7b074f956eac6deb7f0eac729773 to start with?  If so, I explained that I hardly feel the desire to rebuild the image after any given small commit.  This greatly inhibits the convenience factor that docker is supposed to offer--I accept this reality--but I also am operating on the assumption that the docker deployment method of MineOS is both underdeveloped and not highly sought out: so it will only get so much time and energy, considering the very little return I expect to get from it.

> So how do we debug this situation?  Do you really want that I prove you the problem by putting out the commit?  I already did by putting you the commit I had earlier on the webui by rerun a new container...

This is where you need to be more clear of _what needs to be debugged_.  _What_ exactly is the issue you're running into?  That you cannot use `update_webui.sh` and `reset_webui.sh`?  If so, that's of little concern because I have just now demonstrated a known-working method of doing such a reset.  

> So what do you want proof of what version is download like you did?
> Is that the command line to do for that? git log -n 1 | grep commit

I don't know what proof you need to provide to me at all; I have accepted that the docker images are not pulling the most recent commit.  I know this is the case, and I know there is not a clean--or even documented way to update it.  But now I have provided the knowledge of how to have a current webui commit:  either you build from the Dockerfile, which takes all of....3 minutes, each time _or_ you enter the container and run a few commands.

So what _exactly_ are you asking to debug?

**Comment by changemenemo** [comment]
Since it's a buggy version as you and I stated earlier, maybe it could be great that  you just update your push of the image? And so do a docker push yourname/newimage .... ? After all that's all I was asking at first. 
And You stated that you have done different image of docker to know how the rendering was under different os, so now that is done you could maybe have less images? Anyway of course it's just a point of view but then if you don't want to update the image too often then why don't you put the updating process in your UI directly? or even do a cron to update the UI like every day ? 
Do you want me to do it? But anyway you will have to push to the hub yourself because **I'm not for a multiplication of the same docker images**!

my point of view is: if you do something you do it all the way  so if you don't have the courage to keep up to date something that you created, which I'm totally capable of understand, then should we not work on a automatic system?

Docker is a young system. The only way to make people adopt it when they have to virtualize some small process and not big virtual system that needs a real virtualization process, is to make things simple at first and have good documentation. You have a already a good documentation if we put all together all your repositories. But someone who begin in docker won't understand why he just pulled something and it's not working properly, or maybe add a remark point in the readme then no?

By the way I notice that you use the git command.... and I still don't understand all the .js script if you don't use them. Maybe we should'nt use them ? or it was for a cron job only? just tell me what you were planning for it? Or I don't get that the git command call for the js script?

**Comment by hexparrot** [comment]
> then should we not work on a automatic system?

I cannot think of any system (or at least am not familiar with any system) that will auto build my docker files and push them to the hub, much less one that will do the rudimentary test of logging into the webui and checking that a vanilla Minecraft server downloads and runs properly (something I test manually).

If you have any suggestions, we can look into that.

**Comment by changemenemo** [comment]
So some cron jobs to update the UI is not possible in your mind, in the container I mean? Iguess that when you commit something on your mineos-node, you test it before right? So we can easily think about some cronjob no? 

Same thing to update the image to the hub. One cron job based on a good script can easily do the trick.
1/ build the image because of your frequent UI commit + update of java. 
2/ commit image to the hub since it's only a CLI command.

**Comment by changemenemo** [comment]
I really don't see why do you resist so much to the propositions I make. I pushing you since the beginning for cron jobs that could easily update hte UI +/or the docker image. Or maybe you didn't understand it at all ?

**Comment by hexparrot** [comment]
I understand plenty of how cron jobs work. I also know that they don't simply exist in a vacuum. You recommend "create a cron job that runs regularly, creates a new image, and then uploads the new layers to the hub." 

Okay, sure. What computer will be doing this?

**Comment by hexparrot** [comment]
Closing this issue due to difficulty working with you.  You have provided no meaningful insights or recommended any tangible changes but continue to question my ability and condescendingly question my capacity to maintain a dockerfile.
