### ISSUE TITLE
SSH Access

### ISSUE THREAD

**Issue by WhiteNoseThunderPants** [hexparrot/mineos-docker#6]
hexparrot,

Any chance we could get this container to enable SSH access for transferring of plugins and editing files? I'm currently running this container on unRaid and they share all user share over SMB under nobody:nogroup. This makes those files and directories inaccessible that way.

**Comment by hexparrot** [comment]
Docker images shouldn't have SSH servers, [in general](https://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/).  There are good, persistent ways to be able to move plugins and edit files through use of volumes, etc.

That said, I'm not too familiar with unRaid and what that means for the ease of connecting to your dockers.  I'd say, to be honest, that if SSH is an unavoidable necessity, that you definitely can add it to your Dockerfile (and then `docker build` it), but I think most use cases of `mineos-docker` would not benefit from an additional SSHD service running.

**Comment by WhiteNoseThunderPants** [comment]
I'm not familiar with docker outside of unRaid, so I have very little experience with docker. The thing is, all of my other docker containers write everything to the mounted volumes as nobody:nogroup like unRaid likes. MineOS is the only that does not, which is to be expected due to the fact that it uses system user accounts to restrict access to the servers.

I tried to use nobody in the User_NAME environment variable, but as soon as you login to the webui, it crashes and MineOS restarts.

I will try and see what others using unRaid are doing, as I have yet to see anyone else with my particular issue.

Thank you very much for your awesome product, hexparrot, and all the time you spend on support, it is much appreciated!

**Comment by clowrym** [comment]
Not sure if you tried this, I believe I posted it in the unraid forums.....Once the docker creates all the files & folder, I have had to change ownership of all files to 1000:1000 in order for everything to work properly on unraid.

**Comment by Toasterme** [comment]
ssh is the only way to change the default port i think since we have to modify mineos.conf + iptable rules ?
