### ISSUE TITLE
Link dockerhub container to hexparrot/mineos-node

### ISSUE THREAD

**Issue by remyjette** [hexparrot/mineos-docker#7]
Minor suggestion - the container on Dockerhub hexparrot/mineos is fairly out of date (it has commit d9a604b from hexparrot/mineos-node). Just suggesting you add a webhook to cause pushes to hexparrot/mineos-node to trigger rebuilds on Dockerhub

https://github.com/hexparrot/mineos-node/settings/hooks/new

https://docs.docker.com/docker-hub/builds/#remote-build-triggers

**Comment by educatedwarrior** [comment]
Seems like the newer commit may not work.  I've been trying to build a container on my docker host with the latest commit - #8

**Comment by clowrym** [comment]
I had issues building an automated docker with Both Debian and Willy, ubuntu vivid works fine

**Comment by hexparrot** [comment]
I have implemented webhooks to the hub repo:   hexparrot/mineos (deleting the previous repo to use the name instead for autobuilding).

I regrettably didn't do this back in April, much less far, far before then, considering it's ease.

Well, finally it's up and autobuilding on every commit.  Thanks so much for the prompting 👍
